# Generated by Django 5.2.7 on 2025-10-14 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('amenaza_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amenaza',
            },
        ),
        migrations.CreateModel(
            name='Ecosistema',
            fields=[
                ('ecosistema_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ecosistema',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('especie_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre_cientifico', models.CharField(max_length=160, unique=True)),
                ('nombre_comun', models.CharField(blank=True, max_length=160, null=True)),
                ('grupo_taxonomico', models.CharField(max_length=80)),
                ('endemica', models.IntegerField()),
                ('foto_url', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especie',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='EspecieAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.amenaza')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.especie')),
            ],
            options={
                'db_table': 'especie_amenaza',
            },
        ),
        migrations.CreateModel(
            name='EspecieEcosistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecosistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.ecosistema')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.especie')),
            ],
            options={
                'db_table': 'especie_ecosistema',
            },
        ),
        migrations.AddField(
            model_name='ecosistema',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.region'),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comuna_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.region')),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('hash_password', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=20)),
                ('verificado', models.IntegerField()),
                ('fecha_registro', models.DateTimeField()),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.comuna')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('denuncia_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estado', models.CharField(max_length=20)),
                ('autoridad_derivada', models.CharField(blank=True, max_length=160, null=True)),
                ('folio_externo', models.CharField(blank=True, max_length=80, null=True)),
                ('evidencia_url', models.CharField(blank=True, max_length=250, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.usuario')),
            ],
            options={
                'db_table': 'denuncia',
            },
        ),
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('avistamiento_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('precision_m', models.IntegerField(blank=True, null=True)),
                ('metodo', models.CharField(blank=True, max_length=80, null=True)),
                ('evidencia_url', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(max_length=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.especie')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.usuario')),
                ('validado_por', models.ForeignKey(blank=True, db_column='validado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avistamientos_validados', to='App.usuario')),
            ],
            options={
                'db_table': 'avistamiento',
            },
        ),
    ]
