# Generated by Django 5.2.7 on 2025-10-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenaza',
            name='tipo',
            field=models.CharField(choices=[('Contaminación', 'Contaminación'), ('Deforestación', 'Deforestación'), ('Caza furtiva', 'Caza furtiva'), ('Cambio climático', 'Cambio climático'), ('Especies invasoras', 'Especies invasoras'), ('Otro', 'Otro')], max_length=80),
        ),
    ]
