# Generated by Django 5.2.7 on 2025-12-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_amenaza_amenaza_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Investigador', 'Investigador'), ('Usuario', 'Usuario')], max_length=20),
        ),
    ]
